### ISSUE TITLE
Legendary Duelists: Ancient Millennium

### ISSUE THREAD

**Issue by marikisthar** [Ygoproco/Live2017Links#434]
http://yugioh.wikia.com/wiki/Legendary_Duelists:_Ancient_Millennium

could you update their text, names, and Status to TCG????

**Comment by mercury233** [comment]
I suggest that you post SQL of those changes here to help @EerieCode to reduce his work.
You can use the sqldiff tool of sqlite3 to generate SQL of the database you changed.

**Comment by marikisthar** [comment]
Ii already did it, but there's some crash in database

i don't know where

here is the pull I make...

https://github.com/Ygoproco/Live2017Links/pull/430

**Comment by mercury233** [comment]
i mean the sql code such as 'update texts set desc=... where id=100201001'

**Comment by EerieCode** [comment]
@marikisthar We already talked about it yesterday, didn't we? I already said it, I'll upload the changes this weekend, _after_ the set is released, _after_ they update the official database with all info, and, most important of all, _**after**_ we know what changes they've made to older cards. We already know "Rainbow Dragon" got changed, we still don't know if/how they've rewritten "Rainbow Dark Dragon" and "Rainbow Neos", and we have no idea what they've changed with "Crystal Release" and "Violet Crystal" (and we know they've changed _something_, since "Rainbow Bridge" doesn't exclude them explicitly). In cases like this there's more to the update than simply changing the .cdb: for the last time, have patience and let us deal with it, we'll update them once we have all the info we need.

@mercury233 No need to post the SQL, I already have all the files ready. I'm just waiting to see what changes they've made to those older cards I mentioned above, so I can upload everything at once.
